# T1T2_MOOD_IXI_all - MOOD 3T T1 + IXI 3T T1 + IXI 3T T2 + IXI 1.5T T1 + IXI 1.5T T2
_target_: src.datamodules.Datamodules_train.IXI

cfg:
  name: T1T2_MOOD_IXI_all
  path:
    pathBase: ${data_dir}

    IXI:
      IDs: 
        train: 
          - ${data_dir}/Data/splits/T1T2_MOOD_IXI_all_train_fold0.csv
          - ${data_dir}/Data/splits/T1T2_MOOD_IXI_all_train_fold1.csv
          - ${data_dir}/Data/splits/T1T2_MOOD_IXI_all_train_fold2.csv
          - ${data_dir}/Data/splits/T1T2_MOOD_IXI_all_train_fold3.csv
          - ${data_dir}/Data/splits/T1T2_MOOD_IXI_all_train_fold4.csv
        val: 
          - ${data_dir}/Data/splits/T1T2_MOOD_IXI_all_val_fold0.csv
          - ${data_dir}/Data/splits/T1T2_MOOD_IXI_all_val_fold1.csv
          - ${data_dir}/Data/splits/T1T2_MOOD_IXI_all_val_fold2.csv
          - ${data_dir}/Data/splits/T1T2_MOOD_IXI_all_val_fold3.csv
          - ${data_dir}/Data/splits/T1T2_MOOD_IXI_all_val_fold4.csv
        test: ${data_dir}/Data/splits/T1T2_MOOD_IXI_all_test.csv
      keep_t2: ${data_dir}/Data/splits/avail_t2.csv

    Brats21:
      IDs: 
        test: ${data_dir}/Data/splits/Brats21_test.csv
        val: ${data_dir}/Data/splits/Brats21_val.csv

    Brats20_T1:
      IDs: 
        test: ${data_dir}/Data/splits/BraTS_T1_test.csv
        val: ${data_dir}/Data/splits/BraTS_T1_val.csv

    Brats20_T2:
      IDs: 
        test: ${data_dir}/Data/splits/BraTS_T2_test.csv
        val: ${data_dir}/Data/splits/BraTS_T2_val.csv

    MSLUB:
      IDs: 
        test: ${data_dir}/Data/splits/MSLUB_test.csv
        val: ${data_dir}/Data/splits/MSLUB_val.csv

  imageDim: [160,192,160] 
  rescaleFactor: 2
  interRes: [8,8,5]
  cropMode: 'isotropic'
  spatialDims: ${model.cfg.spatialDims}
  unisotropic_sampling: True
  sample_set: False

  preLoad: True
  curvatureFlow: True
  percentile: True
  pad: True
  permute: False

  randomRotate: False
  rotateDegree: 5
  horizontalFlip: False
  randomBrightness: False
  brightnessRange: (0.75,1.25)
  randomContrast: False
  contrastRange: (0.75,1.25)
  
  modelpath: ${data_dir}/Data/pretrained_2D_model/
  num_workers: 4
  batch_size: 32
  lr : 0.0001
  droplast: True
  encoder_mode: end2end
  re_prob: 0.7
  encoder_model: contrastive

  mode: t1t2
  resizedEvaluation: True
  testsets:
  - Datamodules_train.IXI
  - Datamodules_eval.Brats20_T1
  - Datamodules_eval.Brats20_T2
  
